#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevPCI.Modules.DDT_Org_Chart
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="dnn626ce")]
	public partial class DDT_Org_Chart_LinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertDDT_Org_Chart_Node(DDT_Org_Chart_Node instance);
    partial void UpdateDDT_Org_Chart_Node(DDT_Org_Chart_Node instance);
    partial void DeleteDDT_Org_Chart_Node(DDT_Org_Chart_Node instance);
    partial void InsertDDT_Org_Chart_Item(DDT_Org_Chart_Item instance);
    partial void UpdateDDT_Org_Chart_Item(DDT_Org_Chart_Item instance);
    partial void DeleteDDT_Org_Chart_Item(DDT_Org_Chart_Item instance);
    #endregion
		
		public DDT_Org_Chart_LinqDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["SiteSqlServer"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DDT_Org_Chart_LinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDT_Org_Chart_LinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDT_Org_Chart_LinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DDT_Org_Chart_LinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<DDT_Org_Chart_Node> DDT_Org_Chart_Nodes
		{
			get
			{
				return this.GetTable<DDT_Org_Chart_Node>();
			}
		}
		
		public System.Data.Linq.Table<DDT_Org_Chart_Item> DDT_Org_Chart_Items
		{
			get
			{
				return this.GetTable<DDT_Org_Chart_Item>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DDT_Org_Chart_Nodes")]
	public partial class DDT_Org_Chart_Node : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Org_Chart_Node;
		
		private System.Nullable<int> _PortalID;
		
		private System.Nullable<int> _ModuleID;
		
		private System.Nullable<int> _ParentID_Org_Chart_Node;
		
		private string _TeamName_Org_Chart_Node;
		
		private System.Nullable<int> _NodeOrder_Org_Chart;
		
		private System.Nullable<bool> _Collapsed;
		
		private System.Nullable<bool> _GroupCollapsed;
		
		private System.Nullable<int> _ColumnCount;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Org_Chart_NodeChanging(int value);
    partial void OnID_Org_Chart_NodeChanged();
    partial void OnPortalIDChanging(System.Nullable<int> value);
    partial void OnPortalIDChanged();
    partial void OnModuleIDChanging(System.Nullable<int> value);
    partial void OnModuleIDChanged();
    partial void OnParentID_Org_Chart_NodeChanging(System.Nullable<int> value);
    partial void OnParentID_Org_Chart_NodeChanged();
    partial void OnTeamName_Org_Chart_NodeChanging(string value);
    partial void OnTeamName_Org_Chart_NodeChanged();
    partial void OnNodeOrder_Org_ChartChanging(System.Nullable<int> value);
    partial void OnNodeOrder_Org_ChartChanged();
    partial void OnCollapsedChanging(System.Nullable<bool> value);
    partial void OnCollapsedChanged();
    partial void OnGroupCollapsedChanging(System.Nullable<bool> value);
    partial void OnGroupCollapsedChanged();
    partial void OnColumnCountChanging(System.Nullable<int> value);
    partial void OnColumnCountChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    #endregion
		
		public DDT_Org_Chart_Node()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Org_Chart_Node", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Org_Chart_Node
		{
			get
			{
				return this._ID_Org_Chart_Node;
			}
			set
			{
				if ((this._ID_Org_Chart_Node != value))
				{
					this.OnID_Org_Chart_NodeChanging(value);
					this.SendPropertyChanging();
					this._ID_Org_Chart_Node = value;
					this.SendPropertyChanged("ID_Org_Chart_Node");
					this.OnID_Org_Chart_NodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", DbType="Int")]
		public System.Nullable<int> ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentID_Org_Chart_Node", DbType="Int")]
		public System.Nullable<int> ParentID_Org_Chart_Node
		{
			get
			{
				return this._ParentID_Org_Chart_Node;
			}
			set
			{
				if ((this._ParentID_Org_Chart_Node != value))
				{
					this.OnParentID_Org_Chart_NodeChanging(value);
					this.SendPropertyChanging();
					this._ParentID_Org_Chart_Node = value;
					this.SendPropertyChanged("ParentID_Org_Chart_Node");
					this.OnParentID_Org_Chart_NodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TeamName_Org_Chart_Node", DbType="NVarChar(MAX)")]
		public string TeamName_Org_Chart_Node
		{
			get
			{
				return this._TeamName_Org_Chart_Node;
			}
			set
			{
				if ((this._TeamName_Org_Chart_Node != value))
				{
					this.OnTeamName_Org_Chart_NodeChanging(value);
					this.SendPropertyChanging();
					this._TeamName_Org_Chart_Node = value;
					this.SendPropertyChanged("TeamName_Org_Chart_Node");
					this.OnTeamName_Org_Chart_NodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeOrder_Org_Chart", DbType="Int")]
		public System.Nullable<int> NodeOrder_Org_Chart
		{
			get
			{
				return this._NodeOrder_Org_Chart;
			}
			set
			{
				if ((this._NodeOrder_Org_Chart != value))
				{
					this.OnNodeOrder_Org_ChartChanging(value);
					this.SendPropertyChanging();
					this._NodeOrder_Org_Chart = value;
					this.SendPropertyChanged("NodeOrder_Org_Chart");
					this.OnNodeOrder_Org_ChartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collapsed", DbType="Bit")]
		public System.Nullable<bool> Collapsed
		{
			get
			{
				return this._Collapsed;
			}
			set
			{
				if ((this._Collapsed != value))
				{
					this.OnCollapsedChanging(value);
					this.SendPropertyChanging();
					this._Collapsed = value;
					this.SendPropertyChanged("Collapsed");
					this.OnCollapsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GroupCollapsed", DbType="Bit")]
		public System.Nullable<bool> GroupCollapsed
		{
			get
			{
				return this._GroupCollapsed;
			}
			set
			{
				if ((this._GroupCollapsed != value))
				{
					this.OnGroupCollapsedChanging(value);
					this.SendPropertyChanging();
					this._GroupCollapsed = value;
					this.SendPropertyChanged("GroupCollapsed");
					this.OnGroupCollapsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ColumnCount", DbType="Int")]
		public System.Nullable<int> ColumnCount
		{
			get
			{
				return this._ColumnCount;
			}
			set
			{
				if ((this._ColumnCount != value))
				{
					this.OnColumnCountChanging(value);
					this.SendPropertyChanging();
					this._ColumnCount = value;
					this.SendPropertyChanged("ColumnCount");
					this.OnColumnCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DDT_Org_Chart_Items")]
	public partial class DDT_Org_Chart_Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_Org_Chart_Item;
		
		private System.Nullable<int> _PortalID;
		
		private System.Nullable<int> _ModuleID;
		
		private System.Nullable<int> _ID_Org_Chart_Node;
		
		private string _ItemName_Org_Chart;
		
		private string _ItemTitle_Org_Chart;
		
		private string _ItemImageUrl_Org_Chart;
		
		private System.Nullable<int> _ItemOrder_Org_Chart;
		
		private System.Nullable<bool> _Collapsed;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<int> _CreatedByUserID;
		
		private System.Nullable<System.DateTime> _CreatedOnDate;
		
		private System.Nullable<int> _LastModifiedByUserID;
		
		private System.Nullable<System.DateTime> _LastModifiedOnDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_Org_Chart_ItemChanging(int value);
    partial void OnID_Org_Chart_ItemChanged();
    partial void OnPortalIDChanging(System.Nullable<int> value);
    partial void OnPortalIDChanged();
    partial void OnModuleIDChanging(System.Nullable<int> value);
    partial void OnModuleIDChanged();
    partial void OnID_Org_Chart_NodeChanging(System.Nullable<int> value);
    partial void OnID_Org_Chart_NodeChanged();
    partial void OnItemName_Org_ChartChanging(string value);
    partial void OnItemName_Org_ChartChanged();
    partial void OnItemTitle_Org_ChartChanging(string value);
    partial void OnItemTitle_Org_ChartChanged();
    partial void OnItemImageUrl_Org_ChartChanging(string value);
    partial void OnItemImageUrl_Org_ChartChanged();
    partial void OnItemOrder_Org_ChartChanging(System.Nullable<int> value);
    partial void OnItemOrder_Org_ChartChanged();
    partial void OnCollapsedChanging(System.Nullable<bool> value);
    partial void OnCollapsedChanged();
    partial void OnIsActiveChanging(System.Nullable<bool> value);
    partial void OnIsActiveChanged();
    partial void OnIsDeletedChanging(System.Nullable<bool> value);
    partial void OnIsDeletedChanged();
    partial void OnCreatedByUserIDChanging(System.Nullable<int> value);
    partial void OnCreatedByUserIDChanged();
    partial void OnCreatedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnCreatedOnDateChanged();
    partial void OnLastModifiedByUserIDChanging(System.Nullable<int> value);
    partial void OnLastModifiedByUserIDChanged();
    partial void OnLastModifiedOnDateChanging(System.Nullable<System.DateTime> value);
    partial void OnLastModifiedOnDateChanged();
    #endregion
		
		public DDT_Org_Chart_Item()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Org_Chart_Item", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_Org_Chart_Item
		{
			get
			{
				return this._ID_Org_Chart_Item;
			}
			set
			{
				if ((this._ID_Org_Chart_Item != value))
				{
					this.OnID_Org_Chart_ItemChanging(value);
					this.SendPropertyChanging();
					this._ID_Org_Chart_Item = value;
					this.SendPropertyChanged("ID_Org_Chart_Item");
					this.OnID_Org_Chart_ItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this.OnPortalIDChanging(value);
					this.SendPropertyChanging();
					this._PortalID = value;
					this.SendPropertyChanged("PortalID");
					this.OnPortalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModuleID", DbType="Int")]
		public System.Nullable<int> ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this.OnModuleIDChanging(value);
					this.SendPropertyChanging();
					this._ModuleID = value;
					this.SendPropertyChanged("ModuleID");
					this.OnModuleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_Org_Chart_Node", DbType="Int")]
		public System.Nullable<int> ID_Org_Chart_Node
		{
			get
			{
				return this._ID_Org_Chart_Node;
			}
			set
			{
				if ((this._ID_Org_Chart_Node != value))
				{
					this.OnID_Org_Chart_NodeChanging(value);
					this.SendPropertyChanging();
					this._ID_Org_Chart_Node = value;
					this.SendPropertyChanged("ID_Org_Chart_Node");
					this.OnID_Org_Chart_NodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemName_Org_Chart", DbType="NVarChar(MAX)")]
		public string ItemName_Org_Chart
		{
			get
			{
				return this._ItemName_Org_Chart;
			}
			set
			{
				if ((this._ItemName_Org_Chart != value))
				{
					this.OnItemName_Org_ChartChanging(value);
					this.SendPropertyChanging();
					this._ItemName_Org_Chart = value;
					this.SendPropertyChanged("ItemName_Org_Chart");
					this.OnItemName_Org_ChartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemTitle_Org_Chart", DbType="NVarChar(MAX)")]
		public string ItemTitle_Org_Chart
		{
			get
			{
				return this._ItemTitle_Org_Chart;
			}
			set
			{
				if ((this._ItemTitle_Org_Chart != value))
				{
					this.OnItemTitle_Org_ChartChanging(value);
					this.SendPropertyChanging();
					this._ItemTitle_Org_Chart = value;
					this.SendPropertyChanged("ItemTitle_Org_Chart");
					this.OnItemTitle_Org_ChartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemImageUrl_Org_Chart", DbType="NVarChar(MAX)")]
		public string ItemImageUrl_Org_Chart
		{
			get
			{
				return this._ItemImageUrl_Org_Chart;
			}
			set
			{
				if ((this._ItemImageUrl_Org_Chart != value))
				{
					this.OnItemImageUrl_Org_ChartChanging(value);
					this.SendPropertyChanging();
					this._ItemImageUrl_Org_Chart = value;
					this.SendPropertyChanged("ItemImageUrl_Org_Chart");
					this.OnItemImageUrl_Org_ChartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemOrder_Org_Chart", DbType="Int")]
		public System.Nullable<int> ItemOrder_Org_Chart
		{
			get
			{
				return this._ItemOrder_Org_Chart;
			}
			set
			{
				if ((this._ItemOrder_Org_Chart != value))
				{
					this.OnItemOrder_Org_ChartChanging(value);
					this.SendPropertyChanging();
					this._ItemOrder_Org_Chart = value;
					this.SendPropertyChanged("ItemOrder_Org_Chart");
					this.OnItemOrder_Org_ChartChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Collapsed", DbType="Bit")]
		public System.Nullable<bool> Collapsed
		{
			get
			{
				return this._Collapsed;
			}
			set
			{
				if ((this._Collapsed != value))
				{
					this.OnCollapsedChanging(value);
					this.SendPropertyChanging();
					this._Collapsed = value;
					this.SendPropertyChanged("Collapsed");
					this.OnCollapsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this.OnIsActiveChanging(value);
					this.SendPropertyChanging();
					this._IsActive = value;
					this.SendPropertyChanged("IsActive");
					this.OnIsActiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this.OnIsDeletedChanging(value);
					this.SendPropertyChanging();
					this._IsDeleted = value;
					this.SendPropertyChanged("IsDeleted");
					this.OnIsDeletedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedByUserID", DbType="Int")]
		public System.Nullable<int> CreatedByUserID
		{
			get
			{
				return this._CreatedByUserID;
			}
			set
			{
				if ((this._CreatedByUserID != value))
				{
					this.OnCreatedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._CreatedByUserID = value;
					this.SendPropertyChanged("CreatedByUserID");
					this.OnCreatedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreatedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> CreatedOnDate
		{
			get
			{
				return this._CreatedOnDate;
			}
			set
			{
				if ((this._CreatedOnDate != value))
				{
					this.OnCreatedOnDateChanging(value);
					this.SendPropertyChanging();
					this._CreatedOnDate = value;
					this.SendPropertyChanged("CreatedOnDate");
					this.OnCreatedOnDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedByUserID", DbType="Int")]
		public System.Nullable<int> LastModifiedByUserID
		{
			get
			{
				return this._LastModifiedByUserID;
			}
			set
			{
				if ((this._LastModifiedByUserID != value))
				{
					this.OnLastModifiedByUserIDChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedByUserID = value;
					this.SendPropertyChanged("LastModifiedByUserID");
					this.OnLastModifiedByUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastModifiedOnDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastModifiedOnDate
		{
			get
			{
				return this._LastModifiedOnDate;
			}
			set
			{
				if ((this._LastModifiedOnDate != value))
				{
					this.OnLastModifiedOnDateChanging(value);
					this.SendPropertyChanging();
					this._LastModifiedOnDate = value;
					this.SendPropertyChanged("LastModifiedOnDate");
					this.OnLastModifiedOnDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
